name: CD (Build)

on:
  workflow_run:
    workflows:
      - "Python CI"
      - "Node - CI"
    branches:
      - dev
      - stage
      - main
    types:
      - completed

jobs:

  build-python:
    name: Build Python App
    runs-on: ubuntu-latest

    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == 'Python CI'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: apps/python
        run: pip install -r requirements.txt

      - name: Build Python app
        working-directory: apps/python
        run: |
          mkdir -p dist
          cp calculator.py requirements.txt dist/
          echo "Build: ${{ github.event.workflow_run.head_sha }}" > dist/build-info.txt
          ls -lh dist/


  build-node:
    name: Build Node App
    runs-on: ubuntu-latest

    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == 'Node - CI'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: apps/node
        run: npm install

      - name: Build Node app
        working-directory: apps/node
        run: |
          npm pack
          ls -lh *.tgz

